import graniteForm from "./graniteComponents/form/graniteForm";

import "./graniteComponents/form/formStep.css";
const theme = {
  mode: "standard",
};

const profileSettings = {
  id: "form-demo",
  options: {
    title: "",
    addapptation_action: "/",
    description: "",
    title_font_size: "40px",
    description_font_size: "20px",
    db_action: "",
    db_object: "",
    db_id: "g_sf2dsdsf33",
    db_redirect: "",
    flash_message: "",
    position_form: "center",
    form_id: "",
    default_picklists: true,
    button_1_label: "",
    button_1_href: "",
    submit_label: "Save",
    cancel_label: "Cancel",
    max_width: "600px",
    enctype: "application/x-www-form-urlencoded",
    method: "POST",
    visibility_settings: "",
    hide_submit: false,
    allow_cancel: false,
    activate_recaptcha: false,
    auto_superscript: false,
    autosave: false,
    action: "/",
    // Design
    field_bkg_color: "#FFFFFF",
    field_border_color: "#4b4b4b",
    field_border_width: "",
  },
  records: [
    {
      name: "Details",
      type: "step",
      children: [
        {
          type: "text",
          label: "name-label",
          title: "name-title",
          id: "name-id",
          name: "name-name",
          required: true,
          options: "",
          value: "",
          placeholder: "My Super Cool New Scoring Model",
          classes: "g__custom-field",
        },
        {
          type: "textarea",
          label: "name-label",
          title: "name-title",
          id: "name-id",
          name: "name-name",
          required: true,
          options: "",
          value: "",
          placeholder: "My scoring model does a lot of neat things.",
          classes: "g__custom-field",
        },
        {
          type: "header",
          text: "Update Object + Field",
        },
        {
          type: "description",
          text: "Input the field and object your scoring model will update.",
        },
        {
          name: "Update Object + Field",
          type: "fieldset",
          children: [
            {
              type: "text",
              label: "object",
              title: "Object",
              id: "object",
              name: "object",
              required: true,
              options: "",
              value: "",
              placeholder: "ex. Account",
              classes: "g__custom-field",
            },
            {
              type: "text",
              label: "field",
              title: "Field",
              id: "field",
              name: "field",
              required: true,
              options: "",
              value: "",
              placeholder: "ex. Account_Score__c",
              classes: "g__custom-field",
            },
          ],
        },
      ],
    },
    {
      name: "Details",
      type: "step",
      children: [
        {
          type: "header",
          text: "Run Schedule",
        },
        {
          name: "Update Object + Field",
          type: "fieldset",
          children: [
            {
              type: "text",
              label: "object",
              title: "Object",
              id: "object",
              name: "object",
              required: true,
              options: "",
              value: "",
              placeholder: "ex. Account",
              classes: "g__custom-field",
            },
            {
              type: "text",
              label: "field",
              title: "Field",
              id: "field",
              name: "field",
              required: true,
              options: "",
              value: "",
              placeholder: "ex. Account_Score__c",
              classes: "g__custom-field",
            },
          ],
        },
      ],
    },
  ],
};
graniteForm(profileSettings, theme);
